# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - mingw-get update
  - upgrade mingw32-libstdc++
  - mingw-get install mingw32-gmp
  - mingw-get ./configure --prefix=${gmp_install}
  - mingw-get make
  - mingw-get make install
  

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_r devtools
  - travis-tool.sh install_r roxygen2
  - travis-tool.sh install_r testthat
  - travis-tool.sh install_r knitr
  - travis-tool.sh install_r rmarkdown
  - travis-tool.sh install_r Rcpp
  - travis-tool.sh install_r RcppArmadillo
  - travis-tool.sh install_r shiny
  - travis-tool.sh install_r jpeg
  - travis-tool.sh install_r png
  - travis-tool.sh install_r tiff
  - travis-tool.sh install_r covr
  - travis-tool.sh install_r htmltools
  - travis-tool.sh install_r OpenImageR
  - travis-tool.sh install_r graphics
  - travis-tool.sh install_r grDevices
  - travis-tool.sh install_r utils
  - travis-tool.sh install_r gmp
  - travis-tool.sh install_r FD
  - travis-tool.sh install_r stats
  - travis-tool.sh install_r ggplot2
  - travis-tool.sh install_r gtools
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
